### ISSUE TITLE
s should call percentDecode before matching segment

### ISSUE THREAD

**Issue by malaire** [elm/url#20]
`Url.Parser.s` doesn't percentDecode path segments for matching so it returns `Nothing` instead of match if percent-encoding is used.

**Comment by Erudition** [comment]
#16

**Comment by malaire** [comment]
While according to RFC 3986 segments should be percent-decoded before matching, making e.g. segments `%6f`, `%6F` and `o` equivalent, according to newer [URL Living Standard](https://url.spec.whatwg.org/) decoding is not done making those three segments non-equivalent.

The URL Living Standard is a bit vague about the intended behavior so here's an issue I opened about the standard and where I got answer that decoding should not be done: https://github.com/whatwg/url/issues/565
