### ISSUE TITLE
Url.Parser.parse seems to have wrong type signature

### ISSUE THREAD

**Issue by zeninpalm** [elm/url#22]
Hello everyone,
I'm reading Url.Parser source code to understand Elm's url parsing mechanism. I noticed that the type signature of parse function to be:
```elm
parse : Parser (a -> a) a -> Url -> Maybe a
```
Is that signature correct? But I think the correct signature should be:
```elm
parse : Parser (a -> b) b -> Url -> Maybe b
```
Did I misunderstand something here?
Would anyone please give me a hint, thank you very much!

**Comment by evancz** [comment]
These sorts of questions get answered more quickly in community forums, so I recommend asking around on https://discourse.elm-lang.org/ or on http://elmlang.herokuapp.com/ or on https://www.reddit.com/r/elm/
