### ISSUE TITLE
package docs mention non-existing Browser.fullscreen

### ISSUE THREAD

**Issue by youlam** [elm/url#39]
From the second paragraph of the docs (https://package.elm-lang.org/packages/elm/url/latest/Url):

`When you are creating a single-page app with Browser.fullscreen, you use the Url.Parser module to turn a Url into even nicer data.`

However, I cannot find a "fullscreen" function anywhere inside the `Browser` module. (I'm a newbie so correct me if I'm wrong.)

**Comment by evancz** [comment]
Fixed in #11, will come out with next release
