### ISSUE TITLE
Update example for 0.19

### ISSUE THREAD

**Issue by andys8** [elm/url#8]
Meta issue to remind, that the example has to be updated. There will be Elm 0.19 specific changes. But the example is also `"evancz/url-parser": "2.0.0 <= v < 3.0.0"`.

**Comment by andys8** [comment]
https://github.com/elm/url/blob/5d82ea457c6a76da912a0b901093d4d650154910/examples/elm-package.json

**Comment by evancz** [comment]
Should be fixed now.
